/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDeletedLogsRouteImport } from './routes/_app.deleted-logs'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChallansRouteImport } from './routes/_app.challans'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppChallansIndexRouteImport } from './routes/_app.challans.index'
import { Route as AppChallansSentInCourtRouteImport } from './routes/_app.challans.sent-in-court'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDeletedLogsRoute = AppDeletedLogsRouteImport.update({
  id: '/deleted-logs',
  path: '/deleted-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChallansRoute = AppChallansRouteImport.update({
  id: '/challans',
  path: '/challans',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppChallansIndexRoute = AppChallansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChallansRoute,
} as any)
const AppChallansSentInCourtRoute = AppChallansSentInCourtRouteImport.update({
  id: '/sent-in-court',
  path: '/sent-in-court',
  getParentRoute: () => AppChallansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/challans': typeof AppChallansRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/deleted-logs': typeof AppDeletedLogsRoute
  '/challans/sent-in-court': typeof AppChallansSentInCourtRoute
  '/challans/': typeof AppChallansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deleted-logs': typeof AppDeletedLogsRoute
  '/challans/sent-in-court': typeof AppChallansSentInCourtRoute
  '/challans': typeof AppChallansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/challans': typeof AppChallansRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deleted-logs': typeof AppDeletedLogsRoute
  '/_app/challans/sent-in-court': typeof AppChallansSentInCourtRoute
  '/_app/challans/': typeof AppChallansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/challans'
    | '/dashboard'
    | '/deleted-logs'
    | '/challans/sent-in-court'
    | '/challans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/deleted-logs'
    | '/challans/sent-in-court'
    | '/challans'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/challans'
    | '/_app/dashboard'
    | '/_app/deleted-logs'
    | '/_app/challans/sent-in-court'
    | '/_app/challans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/deleted-logs': {
      id: '/_app/deleted-logs'
      path: '/deleted-logs'
      fullPath: '/deleted-logs'
      preLoaderRoute: typeof AppDeletedLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challans': {
      id: '/_app/challans'
      path: '/challans'
      fullPath: '/challans'
      preLoaderRoute: typeof AppChallansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challans/': {
      id: '/_app/challans/'
      path: '/'
      fullPath: '/challans/'
      preLoaderRoute: typeof AppChallansIndexRouteImport
      parentRoute: typeof AppChallansRoute
    }
    '/_app/challans/sent-in-court': {
      id: '/_app/challans/sent-in-court'
      path: '/sent-in-court'
      fullPath: '/challans/sent-in-court'
      preLoaderRoute: typeof AppChallansSentInCourtRouteImport
      parentRoute: typeof AppChallansRoute
    }
  }
}

interface AppChallansRouteChildren {
  AppChallansSentInCourtRoute: typeof AppChallansSentInCourtRoute
  AppChallansIndexRoute: typeof AppChallansIndexRoute
}

const AppChallansRouteChildren: AppChallansRouteChildren = {
  AppChallansSentInCourtRoute: AppChallansSentInCourtRoute,
  AppChallansIndexRoute: AppChallansIndexRoute,
}

const AppChallansRouteWithChildren = AppChallansRoute._addFileChildren(
  AppChallansRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppChallansRoute: typeof AppChallansRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeletedLogsRoute: typeof AppDeletedLogsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppChallansRoute: AppChallansRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDeletedLogsRoute: AppDeletedLogsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
